"""HTTP client for the local model server, plus RAG prompt construction.

All answers are generated by the model server from retrieved knowledge chunks.
No hard-coded FAQ or extractive shortcuts.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from src.core.config import settings
from src.core.logging_config import get_logger

logger = get_logger(__name__)

# Skip heading-only stubs that confuse the model (e.g. "Services Offered by …").
_MIN_CHUNK_WORDS = 20


def _build_session() -> requests.Session:
    session = requests.Session()
    retry = Retry(
        total=settings.model_max_retries,
        backoff_factor=0.5,
        status_forcelist=(500, 502, 503, 504),
        allowed_methods=frozenset({"POST"}),
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    return session


class ModelClient:
    def __init__(self, model_url: Optional[str] = None, timeout: Optional[float] = None):
        self.model_url = model_url or settings.model_url
        self.timeout = timeout or settings.model_timeout
        self._session = _build_session()

    def infer(self, prompt: str) -> Dict[str, Any]:
        try:
            resp = self._session.post(
                self.model_url, json={"input_text": prompt}, timeout=self.timeout
            )
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.RequestException as exc:
            logger.error("Model server request failed: %s", exc)
            return {"error": str(exc)}

    def health(self) -> bool:
        base = self.model_url.rsplit("/", 1)[0] + "/health"
        try:
            resp = self._session.get(base, timeout=5)
            return resp.status_code == 200
        except requests.exceptions.RequestException:
            return False


model_client = ModelClient()


_SERVICE_TITLES = frozenset({
    "Flight Booking", "Visa Assistance", "Hotel Reservations",
    "Umrah and Hajj Packages", "Customized Tour Packages", "Car Rentals",
    "Corporate Travel Management", "World Tours/Pakistan Tours", "Franchise",
})


def _is_services_overview(query: str) -> bool:
    q = (query or "").lower()
    return any(w in q for w in ("service", "services", "offer", "provide", "what do you"))


def _usable_chunks(
    chunks: List[Dict[str, Any]], query: str = "", limit: int = 1
) -> List[Dict[str, Any]]:
    """Pick focused context for the model — one chunk normally, a few for services."""
    ranked = sorted(chunks, key=lambda c: float(c.get("score") or 0.0), reverse=True)
    ranked = [c for c in ranked if len((c.get("content") or "").split()) >= _MIN_CHUNK_WORDS]

    if _is_services_overview(query):
        service = [c for c in ranked if (c.get("title") or "") in _SERVICE_TITLES]
        if service:
            order = {t: i for i, t in enumerate(_SERVICE_TITLES)}
            service.sort(key=lambda c: order.get(c.get("title") or "", 99))
            return service[:6]
        return ranked[:3] if ranked else []

    return ranked[:limit] if ranked else sorted(
        chunks, key=lambda c: float(c.get("score") or 0.0), reverse=True
    )[:1]


def build_prompt(
    query: str,
    chunks: Optional[List[Dict[str, Any]]] = None,
    history: Optional[List[Dict[str, str]]] = None,
) -> str:
    focused = _usable_chunks(chunks or [], query=query)
    if _is_services_overview(query) and focused:
        bullets = []
        for chunk in focused:
            title = (chunk.get("title") or "Service").strip()
            snippet = (chunk.get("content") or "").strip()[:220]
            bullets.append(f"- {title}: {snippet}")
        context_text = (
            "Rehman Travels offers the following services:\n" + "\n".join(bullets)
        )
    else:
        context_parts: List[str] = []
        seen_titles: set[str] = set()
        for chunk in focused:
            title = (chunk.get("title") or "Information").strip()
            if title in seen_titles:
                continue
            seen_titles.add(title)
            content = (chunk.get("content") or "").strip()
            if content:
                context_parts.append(content)
        context_text = "\n\n".join(context_parts)

    history_text = ""
    if history:
        turns = []
        for msg in history[-4:]:
            role = "User" if msg.get("role") == "user" else "Assistant"
            turns.append(f"{role}: {msg.get('content', '').strip()}")
        history_text = "\n".join(turns)

    sections = [
        "You are a helpful travel assistant. Answer the question using ONLY the "
        "passage below. Write a clear, natural answer in 2-4 full sentences. "
        "Include specific prices, destinations, package names and details from "
        "the passage. Do not invent information.",
        f"Question: {query}",
    ]
    if history_text:
        sections.append(f"Recent chat:\n{history_text}")
    if context_text:
        sections.append(f"Passage:\n{context_text}")
    sections.append("Answer:")
    return "\n\n".join(sections)


def generate_answer(
    query: str,
    chunks: Optional[List[Dict[str, Any]]] = None,
    history: Optional[List[Dict[str, str]]] = None,
) -> str:
    """Generate a grounded answer via the model server."""
    if not chunks:
        return settings.fallback_message

    prompt = build_prompt(query, chunks, history)
    result = model_client.infer(prompt)

    if isinstance(result, dict):
        if "response" in result and result["response"]:
            return str(result["response"]).strip()
        if "error" in result:
            logger.warning("Falling back due to model error: %s", result["error"])
            return settings.fallback_message
    return settings.fallback_message


# Backwards-compatible alias used by older imports.
def generate_response(query: str, context=None, language: str = "auto") -> str:
    return generate_answer(query, context)
